name: Convert markdown to Word (convert-and-commit)
on:
  push:
    branches:
      - main

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
          ${for(file)} {"Obituary"},{"EquipmentDistrbution"},{"Assets"},{"Accounts"},{"ComputerSettings"},{"NetworkSettings"}${
          do;
        
      - uses: docker://pandoc/core:2.9
        with:
          args: >- # allows you to break string into multiple lines
             --standalone
             --output=Obituary.docx
             Obituary.md
             pandoc -f $file.md -o $file.pdf
             }
             ${endfor}$

      - name: â¤´ Commit updated version
        run: |
          git config remote.origin.url 'https://${{secrets.GITHUB_TOKEN}}@github.com/RalphHightower/EOL-RalphHightower.git'
          git config user.name RalphHightower
          git config user.email ralph.hightower@gmail.com
          git add .
          git commit -am "update word"
          git push
          done
